Consistent layout (#247)
conclurer/midnightboard pull request #277
Opened 2020-04-17 21:12 UTC by Simon-Deuring

### New
- Consistent layout for all views
### Changes
- All HTML tags use Bootstrap if possible
- Input validation for all fields
- No inline CSS
- Describing comments for all views, components and methods

2020-04-18 16:21 UTC, DevPhilB commented on vue/src/components/BoardSidebar.vue
> +<!-- This sidebar displays all notice board accessable for the user -->
accessable != accessible

2020-04-18 16:23 UTC, DevPhilB commented on vue/src/components/BoardSidebar.vue
> +    // Used to load the all boards accessable for the user
Cf. first comment (change it to accessible)

2020-04-18 16:29 UTC, DevPhilB commented on vue/src/components/NoteFooter.vue
> +<!-- This footer is displayed beneath every note. The deletion button only is shown if the user is authorized to delete it -->
"This footer is displayed under the content of every note. The deletion button is only shown if the user is authorized to delete it" or just "This footer is part of every note. The deletion button is only shown if the user is authorized to delete it"

2020-04-18 16:38 UTC, DevPhilB commented on vue/src/components/cms/PermissionPanel.vue
> +<!-- This panel shows a list of user rights. They can be granted and deprived separately -->
"This panel shows a list of user rights. They can be given and revoked separately"

2020-04-18 16:45 UTC, DevPhilB commented on vue/src/components/cms/UserList.vue
> +     It also allows to promote, demote and delte users -->
"This panel shows a list of all registered users. Each user profil can be visited directly in view- or edit-mode.
"It also allows to promote, demote and delete users"

2020-04-18 16:48 UTC, DevPhilB commented on vue/src/components/cms/UserList.vue
> +    // This method opens the profile page in editing mode
This method opens the profile page in edit mode

2020-04-18 16:51 UTC, DevPhilB commented on vue/src/components/editors/EditorIcon.vue
> +<!-- This class is used to draw the icons visible beneath the text note editor -->
This class is used to draw the icons visible under the text note editor

2020-04-18 17:10 UTC, DevPhilB requested changes
Had to change the base branch to development 👎 
But in general, good job! 👍 
I've added some feedback (w/ solution) and as optional task you could change CSS class names, so that they are consistent too (it looks like you have already started it 😃 )

2020-04-20 12:04 UTC, Simon-Deuring commented
I implemented all your suggestions and changed CSS class names to be standardized.
But I still think that "to grant rights" is better than to "to give rights".

2020-04-20 12:18 UTC, DevPhilB approved these changes
👍

2020-04-20 12:26 UTC, merged